apiVersion: v1
kind: Secret
metadata:
  name: khanhnt15-secret
type: Opaque
data:
  credentials: W2RlZmF1bHRdDQphd3NfYWNjZXNzX2tleV9pZCA9IEFTSUE2TlJNRzNXRjIzSDRGVFBNDQphd3Nfc2VjcmV0X2FjY2Vzc19rZXkgPSB0Z0NUeWhuMkJ3S2Z0K1ZxWEFHWVF2SW81djhjS2xSckp3SG54SHVLDQphd3Nfc2Vzc2lvbl90b2tlbiA9IEZ3b0daWEl2WVhkekVBRWFEQnNZUE1aUTQyVHVNV2FQSlNMVkFaV1RNbjdZSG1xTFh6SENEemQvc1k5aEhDTkJuenY2cmo0aklrYkJZdjVpTEpoazVxVW93dkgwanh4Mjd2K1FJenc0VEFVMzZiTEdtWTNvSkl6QlRjM1NPWWJUekhSeGJzVDVKeE1PdnI0SFBXcFhlRzdoY25CRXZXNjhVZVFhUERrWXc4NHhWc3NpbEFXaUJSbmNoZTlET0x6aktoVUtmWEV4TVowS1FUdWJETVdIS00zUVFpV2ZydjlYN1NvNVh6T2M1QVBQUXJRYTROdUZLdmRHQXQzU3RJQ3BuVVVta2J1M1JYRmhjRW9wbFdocVU2dkdZYXkrVkNFNHhwa29VVnFMUHE3OVRUYXA4c3Y3ZjhWbGsva2RvZDBveHlpTHBheW9Cakl0R1VTbmhIVDkzSGwvTEFKdVhxQnBCQWNGWmQ3Y1hHWm9YU1ZvY3FGZkZEQkJaWVplV2FscW5qVWtSbi8yDQo=